version: 3.2.3
commit: Bump to version v%.%.%
files:
  README.md:
    - license_checker v%.%.%
    - '@kt3k/license_checker@%.%.%'
  main.ts: console.log("%.%.%")
  dnt.ts: 'version: "%.%.%"'
  deno.json: '"version": "%.%.%"'
