version: 3.2.9
commit: Bump to version v%.%.%
files:
  README.md:
    - license-checker v%.%.%
    - '@kt3k/license-checker@%.%.%'
  main.ts: console.log("%.%.%")
  dnt.ts: 'version: "%.%.%"'
  deno.json: '"version": "%.%.%"'
